services:
  postgres-db:
    image: postgres:17-alpine
    shm_size: '2gb'
    container_name: credit_default_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
