CREATE TABLE "companies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vat_number" varchar(11) UNIQUE NOT NULL,
  "legal_name" varchar NOT NULL,
  "legal_form" varchar(50) NOT NULL,
  "industry_sector" varchar(30) NOT NULL,
  "foundation_date" date NOT NULL,
  "registered_office_region" varchar(100),
  "is_active" bool NOT NULL DEFAULT true,
  CHECK (industry_sector IN ('manufacturing', 'chemical_heavy_industry', 'services', 'commerce', 'food_beverage', 'agriculture', 'construction', 'tech', 'hospitality', 'healthcare', 'transportation', 'utilities')),
  CONSTRAINT "past_foundation_date_constraint" CHECK (foundation_date <= CURRENT_DATE)
);

CREATE TABLE "energy_contracts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL,
  "commodity_type" varchar(11) NOT NULL,
  "market_type" varchar(11) NOT NULL,
  "voltage_level" varchar(6),
  "pressure_level" varchar(6),
  "power_committed_kw" decimal(10,2),
  "gas_meter_class" varchar(5),
  "activation_date" date NOT NULL,
  "termination_date" date,
  "contract_status" varchar(10) NOT NULL DEFAULT 'active',
  CONSTRAINT "commodity_type_constraint" CHECK (commodity_type IN ('electricity', 'gas')),
  CONSTRAINT "market_type_constraint" CHECK (market_type IN ('regulated', 'deregulated')),
  CONSTRAINT "voltage_level_constraint" CHECK (voltage_level IN ('low', 'medium', 'high')),
  CONSTRAINT "pressure_level_constraint" CHECK (pressure_level IN ('low', 'medium', 'high')),
  CONSTRAINT "positive_power_committed_constraint" CHECK ((power_committed_kw IS NULL) OR (power_committed_kw > 0)),
  CONSTRAINT "gas_meter_class_constraint" CHECK (gas_meter_class ~ '^G[0-9]+$'),
  CONSTRAINT "electricity_fields_required_constraint" CHECK ((commodity_type != 'electricity') OR (voltage_level IS NOT NULL AND power_committed_kw IS NOT NULL)),
  CONSTRAINT "gas_fields_required_constraint" CHECK ((commodity_type != 'gas') OR (pressure_level IS NOT NULL AND gas_meter_class IS NOT NULL)),
  CONSTRAINT "gas_isolated_fields_constraint" CHECK ((commodity_type != 'gas') OR (voltage_level IS NULL AND power_committed_kw IS NULL)),
  CONSTRAINT "electricity_isolated_fields_constraint" CHECK ((commodity_type != 'electricity') OR (pressure_level IS NULL AND gas_meter_class IS NULL)),
  CONSTRAINT "minimum_activation_date_constraint" CHECK (activation_date >= '2000-01-01'),
  CONSTRAINT "contract_date_chronology_constraint" CHECK (termination_date > activation_date),
  CONSTRAINT "terminated_contract_date_required_constraint" CHECK ((contract_status != 'terminated') OR (termination_date IS NOT NULL)),
  CONSTRAINT "contract_status_constraint" CHECK (contract_status IN ('active', 'suspended', 'terminated'))
);

CREATE TABLE "financial_statements" (
  "company_id" bigint NOT NULL,
  "fiscal_year" integer NOT NULL,
  "total_revenue" decimal(15,2) NOT NULL,
  "net_income" decimal(15,2) NOT NULL,
  "total_debt" decimal(15,2) NOT NULL,
  "liquidity_cash" decimal(15,2) NOT NULL,
  "share_capital" decimal(15,2) NOT NULL,
  "ebitda" decimal(15,2) NOT NULL,
  CONSTRAINT "fiscal_year_constraint" CHECK (fiscal_year >= 2000),
  CONSTRAINT "positive_revenue_constraint" CHECK (total_revenue >= 0),
  CONSTRAINT "positive_share_capital_constraint" CHECK (share_capital >= 0),
  CONSTRAINT "positive_total_debt_constraint" CHECK (total_debt >= 0),
  CONSTRAINT "positive_liquidity_cash_constraint" CHECK (liquidity_cash >= 0),
  PRIMARY KEY ("company_id", "fiscal_year")
);

CREATE TABLE "invoices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contract_id" bigint NOT NULL,
  "commodity_type" varchar(11) NOT NULL,
  "invoice_number" varchar(50) UNIQUE NOT NULL,
  "energy_consumption_kwh" decimal(10,2),
  "gas_consumption_scm" decimal(10,2),
  "amount_excluding_tax" decimal(15,2) NOT NULL,
  "tax_amount" decimal(15,2) NOT NULL,
  "total_amount" decimal(15,2) NOT NULL,
  "issue_date" date NOT NULL,
  "due_date" date NOT NULL,
  "invoice_status" varchar(20) NOT NULL DEFAULT 'unpaid',
  CONSTRAINT "invoice_date_chronology_constraint" CHECK (due_date >= issue_date),
  CONSTRAINT "invoice_amount_integrity_constraint" CHECK (total_amount = (amount_excluding_tax + tax_amount)),
  CONSTRAINT "invoice_status_constraint" CHECK (invoice_status IN ('unpaid', 'paid', 'overdue', 'cancelled')),
  CONSTRAINT "invoice_commodity_type_constraint" CHECK (commodity_type IN ('electricity', 'gas')),
  CONSTRAINT "positive_invoice_amount_constraint" CHECK (amount_excluding_tax >= 0),
  CONSTRAINT "positive_tax_amount_constraint" CHECK (tax_amount >= 0),
  CONSTRAINT "positive_electricity_consumption_constraint" CHECK ((energy_consumption_kwh IS NULL) OR (energy_consumption_kwh >= 0)),
  CONSTRAINT "positive_gas_consumption_constraint" CHECK ((gas_consumption_scm IS NULL) OR (gas_consumption_scm >= 0)),
  CONSTRAINT "electricity_consumption_integrity_constraint" CHECK ((commodity_type != 'electricity') OR (energy_consumption_kwh IS NOT NULL AND gas_consumption_scm IS NULL)),
  CONSTRAINT "gas_consumption_integrity_constraint" CHECK ((commodity_type != 'gas') OR (gas_consumption_scm IS NOT NULL AND energy_consumption_kwh IS NULL))
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" bigint NOT NULL,
  "payment_date" date NOT NULL,
  "amount_paid" decimal(15,2) NOT NULL,
  "payment_method" varchar(25) NOT NULL,
  "transaction_reference" varchar(100) UNIQUE,
  "payment_status" varchar(20) NOT NULL DEFAULT 'completed',
  CONSTRAINT "payment_method_constraint" CHECK (payment_method IN ('direct_debit', 'bank_transfer', 'credit_card', 'postal_bulletin', 'cash')),
  CONSTRAINT "payment_status_constraint" CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
  CONSTRAINT "positive_payment_amount_constraint" CHECK (amount_paid > 0),
  CONSTRAINT "past_payment_date_constraint" CHECK (payment_date <= CURRENT_DATE)
);

CREATE TABLE "crm_support_tickets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL,
  "ticket_category" varchar(30) NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "resolved_at" timestamptz,
  "satisfaction_score" integer,
  CONSTRAINT "ticket_date_chronology_constraint" CHECK (resolved_at >= created_at),
  CONSTRAINT "satisfaction_score_range_constraint" CHECK (satisfaction_score BETWEEN 1 AND 5),
  CONSTRAINT "resolved_ticket_score_dependency_constraint" CHECK ((resolved_at IS NOT NULL) OR (satisfaction_score IS NULL)),
  CONSTRAINT "ticket_category_constraint" CHECK (ticket_category IN ('billing', 'technical', 'onboarding', 'commercial')),
  CONSTRAINT "past_ticket_creation_constraint" CHECK (created_at <= CURRENT_TIMESTAMP)
);

CREATE TABLE "user_web_logins" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "login_timestamp" timestamptz NOT NULL DEFAULT (now()),
  "ip_address" inet NOT NULL,
  "device_type" varchar(20) NOT NULL,
  CONSTRAINT "device_type_constraint" CHECK (device_type IN ('desktop', 'mobile', 'tablet', 'api')),
  CONSTRAINT "past_login_timestamp_constraint" CHECK (login_timestamp <= CURRENT_TIMESTAMP)
);

CREATE UNIQUE INDEX ON "energy_contracts" ("id", "commodity_type");

CREATE INDEX ON "energy_contracts" ("company_id");

CREATE INDEX "ix_invoices_fk_contract_commodity" ON "invoices" ("contract_id", "commodity_type");

CREATE INDEX "ix_invoices_operational_status" ON "invoices" ("invoice_status");

CREATE INDEX ON "payments" ("invoice_id");

CREATE INDEX ON "crm_support_tickets" ("company_id");

CREATE INDEX ON "user_web_logins" ("company_id");

CREATE INDEX "ix_logins_user_timeline" ON "user_web_logins" ("user_id", "login_timestamp");

ALTER TABLE "energy_contracts" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "financial_statements" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crm_support_tickets" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_web_logins" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("contract_id", "commodity_type") REFERENCES "energy_contracts" ("id", "commodity_type") DEFERRABLE INITIALLY IMMEDIATE;
