CREATE TABLE "companies" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vat_number" varchar(11) UNIQUE NOT NULL,
  "legal_name" varchar NOT NULL,
  "legal_form" varchar(50) NOT NULL,
  "industry_sector" varchar(30) NOT NULL,
  "foundation_date" date NOT NULL,
  "registered_office_region" varchar(100),
  "is_active" bool NOT NULL DEFAULT true,
  CHECK (industry_sector IN ('manufacturing', 'chemical_heavy_industry', 'services', 'commerce', 'food_beverage', 'agriculture', 'construction', 'tech', 'hospitality', 'healthcare', 'transportation', 'utilities'))
);

CREATE TABLE "energy_contracts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL,
  "commodity_type" varchar(11) NOT NULL,
  "market_type" varchar(11) NOT NULL,
  "voltage_level" varchar(6),
  "pressure_level" varchar(6),
  "power_committed_kw" decimal(10,2),
  "gas_meter_class" varchar(5),
  "activation_date" date NOT NULL,
  "termination_date" date,
  "contract_status" varchar(10) NOT NULL DEFAULT 'active',
  CONSTRAINT "commodity_type_constraint" CHECK (commodity_type IN ('electricity', 'gas')),
  CONSTRAINT "market_type_constraint" CHECK (market_type IN ('regulated', 'deregulated')),
  CONSTRAINT "voltage_level_constraint" CHECK (voltage_level IN ('low', 'medium', 'high')),
  CONSTRAINT "pressure_level_constraint" CHECK (pressure_level IN ('low', 'medium', 'high')),
  CONSTRAINT "gas_meter_class_constraint" CHECK (gas_meter_class ~ '^G[0-9]+$'),
  CONSTRAINT "electricity_fields_required_constraint" CHECK ((commodity_type != 'electricity') OR (voltage_level IS NOT NULL AND power_committed_kw IS NOT NULL)),
  CONSTRAINT "gas_fields_required_constraint" CHECK ((commodity_type != 'gas') OR (pressure_level IS NOT NULL AND gas_meter_class IS NOT NULL)),
  CONSTRAINT "contract_date_chronology_constraint" CHECK (termination_date > activation_date),
  CONSTRAINT "contract_status_constraint" CHECK (contract_status IN ('active', 'suspended', 'terminated'))
);

CREATE TABLE "financial_statements" (
  "company_id" bigint NOT NULL,
  "fiscal_year" integer NOT NULL,
  "total_revenue" decimal(15,2) NOT NULL,
  "net_income" decimal(15,2) NOT NULL,
  "total_debt" decimal(15,2) NOT NULL,
  "liquidity_cash" decimal(15,2) NOT NULL,
  "share_capital" decimal(15,2) NOT NULL,
  "ebitda" decimal(15,2) NOT NULL,
  CONSTRAINT "fiscal_year_costraint" CHECK (fiscal_year >= 2000),
  PRIMARY KEY ("company_id", "fiscal_year")
);

CREATE TABLE "invoices" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "contract_id" bigint NOT NULL,
  "commodity_type" varchar(11) NOT NULL,
  "invoice_number" varchar(50) UNIQUE NOT NULL,
  "energy_consumption_kwh" decimal(10,2),
  "gas_consumption_scm" decimal(10,2),
  "amount_excluding_tax" decimal(15,2) NOT NULL,
  "tax_amount" decimal(15,2) NOT NULL,
  "total_amount" decimal(15,2) NOT NULL,
  "issue_date" date NOT NULL,
  "due_date" date NOT NULL,
  "invoice_status" varchar(20) NOT NULL DEFAULT 'unpaid',
  CONSTRAINT "invoice_date_chronology_constraint" CHECK (due_date >= issue_date),
  CONSTRAINT "invoice_amount_integrity_constraint" CHECK (total_amount = (amount_excluding_tax + tax_amount)),
  CONSTRAINT "invoice_status_constraint" CHECK (invoice_status IN ('unpaid', 'paid', 'overdue', 'cancelled')),
  CONSTRAINT "invoice_commodity_type_constraint" CHECK (commodity_type IN ('electricity', 'gas')),
  CONSTRAINT "electricity_consumption_integrity_constraint" CHECK ((commodity_type != 'electricity') OR (energy_consumption_kwh IS NOT NULL AND gas_consumption_scm IS NULL)),
  CONSTRAINT "gas_consumption_integrity_constraint" CHECK ((commodity_type != 'gas') OR (gas_consumption_scm IS NOT NULL AND energy_consumption_kwh IS NULL))
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "invoice_id" bigint NOT NULL,
  "payment_date" date NOT NULL,
  "amount_paid" decimal(15,2) NOT NULL,
  "payment_method" varchar(25) NOT NULL,
  "transaction_reference" varchar(100) UNIQUE,
  "payment_status" varchar(20) NOT NULL DEFAULT 'completed',
  CONSTRAINT "payment_method_constraint" CHECK (payment_method IN ('direct_debit', 'bank_transfer', 'credit_card', 'postal_bulletin', 'cash')),
  CONSTRAINT "payment_status_constraint" CHECK (payment_status IN ('pending', 'completed', 'failed', 'refunded')),
  CONSTRAINT "positive_payment_amount_constraint" CHECK (amount_paid > 0)
);

CREATE TABLE "crm_support_tickets" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL,
  "ticket_category" varchar(30) NOT NULL,
  "created_at" timestampz NOT NULL DEFAULT (now()),
  "resolved_at" timestampz,
  "satisfaction_score" integer,
  CONSTRAINT "ticket_date_chronology_constraint" CHECK (resolved_at >= created_at),
  CONSTRAINT "satisfaction_score_range_constraint" CHECK (satisfaction_score BETWEEN 1 AND 5),
  CONSTRAINT "ticket_category_constraint" CHECK (ticket_category IN ('billing', 'technical', 'onboarding', 'commercial'))
);

CREATE TABLE "user_web_logins" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "company_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "login_timestamp" timestampz NOT NULL DEFAULT (now()),
  "ip_address" varchar(45) NOT NULL,
  "device_type" varchar(20) NOT NULL,
  CONSTRAINT "device_type_constraint" CHECK (device_type IN ('desktop', 'mobile', 'tablet', 'api')),
  CONSTRAINT "minimum_ip_length_constraint" CHECK (length(ip_address) >= 7)
);

CREATE INDEX ON "companies" ("legal_form");

CREATE UNIQUE INDEX ON "energy_contracts" ("id", "commodity_type");

CREATE INDEX ON "energy_contracts" ("company_id");

CREATE INDEX ON "energy_contracts" ("contract_status");

CREATE INDEX ON "financial_statements" ("total_debt");

CREATE INDEX ON "invoices" ("total_amount");

CREATE INDEX ON "invoices" ("invoice_status");

CREATE INDEX ON "payments" ("invoice_id");

CREATE INDEX ON "payments" ("amount_paid");

CREATE INDEX ON "payments" ("payment_status");

CREATE INDEX ON "crm_support_tickets" ("company_id");

CREATE INDEX ON "crm_support_tickets" ("ticket_category");

CREATE INDEX ON "crm_support_tickets" ("created_at");

CREATE INDEX ON "user_web_logins" ("company_id");

CREATE INDEX ON "user_web_logins" ("user_id");

CREATE INDEX ON "user_web_logins" ("login_timestamp");

ALTER TABLE "energy_contracts" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "financial_statements" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("contract_id") REFERENCES "energy_contracts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "crm_support_tickets" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_web_logins" ADD FOREIGN KEY ("company_id") REFERENCES "companies" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "invoices" ADD FOREIGN KEY ("contract_id", "commodity_type") REFERENCES "energy_contracts" ("id", "commodity_type") DEFERRABLE INITIALLY IMMEDIATE;
