"""feat: create database structure

Revision ID: 4c84a2bf5287
Revises:
Create Date: 2026-07-09 15:34:43.661055

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "4c84a2bf5287"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
