"""feat: create database structure (really, this time)

Revision ID: c1cf595229f7
Revises: 7f2797ec0404
Create Date: 2026-07-11 20:14:57.373379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import database.types

# revision identifiers, used by Alembic.
revision: str = 'c1cf595229f7'
down_revision: Union[str, Sequence[str], None] = '7f2797ec0404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('vat_number', sa.String(length=11), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=False),
    sa.Column('legal_form', sa.String(length=50), nullable=False),
    sa.Column('industry_sector', sa.String(length=30), nullable=False),
    sa.Column('foundation_date', sa.Date(), nullable=False),
    sa.Column('registered_office_region', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("industry_sector IN (\n                'manufacturing',\n                'chemical_heavy_industry',\n                'services',\n                'commerce',\n                'food_beverage',\n                'agriculture',\n                'construction',\n                'tech',\n                'hospitality',\n                'healthcare',\n                'transportation',\n                'utilities')", name='industry_sector_constraint'),
    sa.CheckConstraint('foundation_date <= CURRENT_DATE', name='past_foundation_date_constraint'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vat_number')
    )
    op.create_table('crm_support_tickets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ticket_category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('satisfaction_score', sa.Integer(), nullable=True),
    sa.CheckConstraint("ticket_category IN (\n                'billing',\n                'technical',\n                'onboarding',\n                'commercial')", name='ticket_category_constraint'),
    sa.CheckConstraint('(resolved_at IS NOT NULL) OR\n            (satisfaction_score IS NULL)', name='resolved_ticket_score_dependency_constraint'),
    sa.CheckConstraint('created_at <= CURRENT_TIMESTAMP', name='past_ticket_creation_constraint'),
    sa.CheckConstraint('resolved_at >= created_at', name='ticket_date_chronology_constraint'),
    sa.CheckConstraint('satisfaction_score BETWEEN 1 AND 5', name='satisfaction_score_range_constraint'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crm_support_tickets_company_id', 'crm_support_tickets', ['company_id'], unique=False)
    op.create_table('energy_contracts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('commodity_type', sa.String(length=11), nullable=False),
    sa.Column('market_type', sa.String(length=11), nullable=False),
    sa.Column('voltage_level', sa.String(length=6), nullable=True),
    sa.Column('pressure_level', sa.String(length=6), nullable=True),
    sa.Column('power_committed_kw', database.types.ExactNumeric(precision=10, scale=2), nullable=True),
    sa.Column('gas_meter_class', sa.String(length=5), nullable=True),
    sa.Column('activation_date', sa.Date(), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('contract_status', sa.String(length=10), server_default=sa.text("'active'"), nullable=False),
    sa.CheckConstraint("(commodity_type != 'electricity') OR\n            (pressure_level IS NULL AND\n            gas_meter_class IS NULL)", name='electricity_isolated_fields_constraint'),
    sa.CheckConstraint("(commodity_type != 'electricity') OR\n            (voltage_level IS NOT NULL AND\n            power_committed_kw IS NOT NULL)", name='electricity_fields_required_constraint'),
    sa.CheckConstraint("(commodity_type != 'gas') OR\n            (pressure_level IS NOT NULL AND\n            gas_meter_class IS NOT NULL)", name='gas_fields_required_constraint'),
    sa.CheckConstraint("(commodity_type != 'gas') OR\n            (voltage_level IS NULL AND\n            power_committed_kw IS NULL)", name='gas_isolated_fields_constraint'),
    sa.CheckConstraint("(contract_status != 'terminated') OR\n            (termination_date IS NOT NULL)", name='terminated_contract_date_required_constraint'),
    sa.CheckConstraint("activation_date >= '2000-01-01'", name='minimum_activation_date_constraint'),
    sa.CheckConstraint("commodity_type IN (\n                'electricity',\n                'gas')", name='commodity_type_constraint'),
    sa.CheckConstraint("contract_status IN (\n                'active',\n                'suspended',\n                'terminated')", name='contract_status_constraint'),
    sa.CheckConstraint("gas_meter_class LIKE 'G%%'", name='gas_meter_class_constraint'),
    sa.CheckConstraint("market_type IN (\n                'regulated',\n                'deregulated')", name='market_type_constraint'),
    sa.CheckConstraint("pressure_level IN (\n                'low',\n                'medium',\n                'high')", name='pressure_level_constraint'),
    sa.CheckConstraint("voltage_level IN (\n                'low',\n                'medium',\n                'high')", name='voltage_level_constraint'),
    sa.CheckConstraint('(power_committed_kw IS NULL) OR\n            (power_committed_kw > 0)', name='positive_power_committed_constraint'),
    sa.CheckConstraint('termination_date > activation_date', name='contract_date_chronology_constraint'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_energy_contracts_company_id', 'energy_contracts', ['company_id'], unique=False)
    op.create_index('uq_energy_contracts_id_commodity', 'energy_contracts', ['id', 'commodity_type'], unique=True)
    op.create_table('financial_statements',
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('total_revenue', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('net_income', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('total_debt', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('liquidity_cash', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('share_capital', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('ebitda', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.CheckConstraint('fiscal_year >= 2000', name='fiscal_year_constraint'),
    sa.CheckConstraint('liquidity_cash >= 0', name='positive_liquidity_cash_constraint'),
    sa.CheckConstraint('share_capital >= 0', name='positive_share_capital_constraint'),
    sa.CheckConstraint('total_debt >= 0', name='positive_total_debt_constraint'),
    sa.CheckConstraint('total_revenue >= 0', name='positive_revenue_constraint'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('company_id', 'fiscal_year')
    )
    op.create_table('user_web_logins',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('login_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', postgresql.INET().with_variant(sa.String(length=45), 'sqlite'), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("device_type IN (\n                'desktop',\n                'mobile',\n                'tablet',\n                'api')", name='device_type_constraint'),
    sa.CheckConstraint('login_timestamp <= CURRENT_TIMESTAMP', name='past_login_timestamp_constraint'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logins_user_timeline', 'user_web_logins', ['user_id', sa.literal_column('login_timestamp DESC')], unique=False)
    op.create_index('idx_user_web_logins_company_id', 'user_web_logins', ['company_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('commodity_type', sa.String(length=11), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('electricity_consumption_kwh', database.types.ExactNumeric(precision=10, scale=2), nullable=True),
    sa.Column('gas_consumption_scm', database.types.ExactNumeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_excluding_tax', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('tax_amount', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('total_amount', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('invoice_status', sa.String(length=20), server_default=sa.text("'unpaid'"), nullable=False),
    sa.CheckConstraint("(commodity_type != 'electricity') OR\n            (electricity_consumption_kwh IS NOT NULL AND\n            gas_consumption_scm IS NULL)", name='electricity_consumption_integrity_constraint'),
    sa.CheckConstraint("(commodity_type != 'gas') OR\n            (gas_consumption_scm IS NOT NULL AND\n            electricity_consumption_kwh IS NULL)", name='gas_consumption_integrity_constraint'),
    sa.CheckConstraint("commodity_type IN (\n                'electricity',\n                'gas')", name='invoice_commodity_type_constraint'),
    sa.CheckConstraint("invoice_status IN (\n                'unpaid',\n                'paid',\n                'overdue',\n                'cancelled')", name='invoice_status_constraint'),
    sa.CheckConstraint('(electricity_consumption_kwh IS NULL) OR\n            (electricity_consumption_kwh >= 0)', name='positive_electricity_consumption_constraint'),
    sa.CheckConstraint('(gas_consumption_scm IS NULL) OR\n            (gas_consumption_scm >= 0)', name='positive_gas_consumption_constraint'),
    sa.CheckConstraint('amount_excluding_tax >= 0', name='positive_invoice_amount_constraint'),
    sa.CheckConstraint('due_date >= issue_date', name='invoice_date_chronology_constraint'),
    sa.CheckConstraint('tax_amount >= 0', name='positive_tax_amount_constraint'),
    sa.CheckConstraint('total_amount = (amount_excluding_tax + tax_amount)', name='invoice_amount_integrity_constraint'),
    sa.ForeignKeyConstraint(['contract_id', 'commodity_type'], ['energy_contracts.id', 'energy_contracts.commodity_type'], name='commodity_type_composite_fk_constraint', initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('idx_invoices_fk_contract_commodity', 'invoices', ['contract_id', 'commodity_type'], unique=False)
    op.create_index('idx_invoices_operational_status', 'invoices', ['invoice_status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', database.types.ExactNumeric(precision=15, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=25), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_status', sa.String(length=20), server_default=sa.text("'completed'"), nullable=False),
    sa.CheckConstraint("payment_method IN (\n                'direct_debit',\n                'bank_transfer',\n                'credit_card',\n                'postal_bulletin',\n                'cash')", name='payment_method_constraint'),
    sa.CheckConstraint("payment_status IN (\n                'pending',\n                'completed',\n                'failed',\n                'refunded')", name='payment_status_constraint'),
    sa.CheckConstraint('amount_paid > 0', name='positive_payment_amount_constraint'),
    sa.CheckConstraint('payment_date <= CURRENT_DATE', name='past_payment_date_constraint'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], initially='IMMEDIATE', deferrable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index('idx_payments_invoice_id', 'payments', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_invoice_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_invoices_operational_status', table_name='invoices')
    op.drop_index('idx_invoices_fk_contract_commodity', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_user_web_logins_company_id', table_name='user_web_logins')
    op.drop_index('idx_logins_user_timeline', table_name='user_web_logins')
    op.drop_table('user_web_logins')
    op.drop_table('financial_statements')
    op.drop_index('uq_energy_contracts_id_commodity', table_name='energy_contracts')
    op.drop_index('idx_energy_contracts_company_id', table_name='energy_contracts')
    op.drop_table('energy_contracts')
    op.drop_index('idx_crm_support_tickets_company_id', table_name='crm_support_tickets')
    op.drop_table('crm_support_tickets')
    op.drop_table('companies')
    # ### end Alembic commands ###
