"""In-memory conversation session store for the chat endpoint.

The CLI agent (`agent.run_agent`) keeps conversation history as a single
Python list local to its loop, since it only ever serves one user at a time.
An HTTP server is stateless between requests and may serve many concurrent
users, so this module keeps one message history per `session_id` instead of
a single global list. Storage is a plain in-memory dict: state is lost on
restart and is not shared across multiple server instances. That is an
accepted limitation for a no-cloud version.

"""

from schemas.api.session_validation import Message


class SessionStore:
    """Keep one conversation history per session, in memory.

    The internal dict maps a `session_id` to its list of `Message`s, in
    chronological order. Callers should not access the internal dict
    directly; use `get_history` and `append_turn` instead, so the storage
    implementation can change later without affecting callers.

    """

    def __init__(self) -> None:
        """Initialize an empty store with no sessions."""
        self.sessions: dict[str, list[Message]] = {}

    def get_history(self, session_id: str) -> list[Message]:
        """Return the message history for a session.

        Args:
            session_id: the identifier of the conversation, as generated by
                the client (e.g. a UUID sent in a request header).

        Returns:
            list[Message]: the conversation history so far, in
                chronological order. An empty list if the session is new.

        """
        return self.sessions.setdefault(session_id, [])

    def append_turn(self, session_id: str, user_input: str, final_answer: str) -> None:
        """Append one user/assistant turn to a session's history.

        Args:
            session_id: the identifier of the conversation to update.
            user_input: the raw text the user sent for this turn.
            final_answer: the agent's final answer for this turn.

        """
        history = self.sessions.setdefault(session_id, [])
        history.append(Message(role="user", content=user_input))
        history.append(Message(role="assistant", content=final_answer))


session_store = SessionStore()
